obj-$(CONFIG_MSM_QDSP6V2_CODECS) += audio_native.o aac_in.o qcelp_in.o evrc_in.o amrnb_in.o
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += g711mlaw_in.o g711alaw_in.o audio_utils.o
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += audio_wma.o audio_wmapro.o 
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += audio_aac.o audio_multi_aac.o audio_alac.o audio_ape.o audio_utils_aio.o
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += q6audio_v2.o q6audio_v2_aio.o
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += audio_g711mlaw.o audio_g711alaw.o
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += audio_mp3.o audio_amrnb.o audio_amrwb.o audio_amrwbplus.o audio_evrc.o 
obj-$(CONFIG_MSM_QDSP6V2_CODECS) += audio_qcelp.o amrwb_in.o audio_hwacc_effects.o
