snd-soc-analog-cdc-objs := sdm660-cdc-irq.o msm-analog-cdc.o
snd-soc-digital-cdc-objs := msm-digital-cdc.o msm-digital-cdc-regmap.o
snd-soc-digital-cdc-legacy-objs := msm-digital-cdc-legacy.o msm-digital-cdc-legacy-regmap.o

obj-$(CONFIG_SND_SOC_ANALOG_CDC) += snd-soc-analog-cdc.o
obj-$(CONFIG_SND_SOC_DIGITAL_CDC) += snd-soc-digital-cdc.o
obj-$(CONFIG_SND_SOC_DIGITAL_CDC_LEGACY) += snd-soc-digital-cdc-legacy.o
